[PRIORS]
\log_{10}{P_0} = free , flat_prior , 7.2 | 9
P_{M} = free , gaussian_prior_truncated, 0.66 | 0.5 | 0 | 3
P_{z} = free , gaussian_prior_truncated, 2.66 | 0.5 | 1 | 4
gamma_0 = free , flat_prior, 0 | 2.5
gamma_M = free , t_student_prior_truncated, 1 | 0 | 0 | 2
gamma_z = free , t_student_prior_truncated, 1 | 0 | -2 | 2
beta = fixed, 4.13
; t_student_prior_truncated, 1 | 0 | 0 | 6
alpha = fixed, 1.33
;t_student_prior_truncated, 1 | 0 | 0 | 6
\log_{10}{r_s} = free , flat_prior , -0.2 | 0.4
[PRIORS_MIS_CENTERING]
f_{mis} = free, gaussian_prior_truncated , 0.26 | 0.05 | 0.0 | 0.6
; f_{M} = free, t_student_prior_truncated, 1 | 0 | -0.1 | 0.1
; f_{z} = free, t_student_prior_truncated, 1 | 0 | -0.1 | 0.1
sigma_{mis} = free, gaussian_prior_truncated , 0.35 | 0.05 | 0.1 | 1
[PRIORS_HALO_MODEL]
\log_{10}{A_{\lambda-M}} : free , gaussian_prior_truncated, 30 | 0.5 | 25 | 35
F_{\lambda} : free, gaussian_prior_truncated, 0.75 | 0.05 | 0.65 | 0.85
G_{z} : free, gaussian_prior_truncated, 0 | 0.01 | -1 | 1
[MODEL]
rbins = 35
zbins = 30
Mbins = 25
profile = ycompton_general2M200
richness_pivot = 32.68
redshift_pivot = 0.40865
mass_pivot = 14.8816
two_halo_term = True
mis_centering = True
rebinning = True
name = TSZ
y = $\langle_y \rangle$, 
x = R,arcmin
yscale = log
xscale = linear
ymin = 1e-7
ymax = 1e-3
title = ACT ycompton profile
model_name= GNFW
rotate_cov_matrix = False
use_filters = True
apply_filter_per_profile = False
filters = dict(apply_beam = dict(fwhm = 1.6))
off_diag = False
delta = 200
background = critical
eval_mass = True
legend_pos = upper left
[EMCEE]
nwalkers = 50
nsteps = 15000
output_file = mcmc_samples_y_generalM200_mc, h5
rewrite = True
delete = True
likelihood = gaussian
ncores = 39
store_two_halo_term = True
[BLOBS]
CHI2 = np.float64 , (1)
LN_PRIOR = np.float64 , (1)
LN_LIKELIHOOD = np.float64 , (1)
SIGNAL= np.float64 , (42)
ONE_HALO = np.float64, (42)
TWO_HALO = np.float64, (42)
[TWO_HALO_TERM]
R = -3, 1.7, 30, log
M = 13, 16, 30, log
k = -15, 15, 40, log
background = critical
delta = 200
two_halo_power = False
two_halo_power_func = linear
eval_only_mass = False
eval_only_richness = False
eval_only_redshift = False
[PRIORS_TWO_HALO_POWER]
A_{2h} = free, flat_prior, 0 | 2.5
A_{z,2h} = free, t_student_prior_truncated, 1, 0, -2, 2
[MIS_CENTERING]
Roff = 0, 2, 20, linear
theta = 0, 6.28318, 25, linear
fixed = False
fmis = 0.246
params = 0.385
func = mis_centering_model
[REBINNING]
Nbins = 30
pixel_size = 0.5
method = spline
interpolation_kwargs = dict(k=1, s=0)
[COMPLETENESS]
use_redshift = True
eval_lambda_true = True
fixed_RM_relationship = True
load_from_file = False
func = 'P_lob_ltr'
rbins = 35
zbins = 30
Mbins = 25
max_lambda_true = 350
min_lambda_true = 10
Nlambda_obs = 20
Nlambda_true = 50
completeness_kwargs = dict(completenes_file = "/data2/cristobal/actpol/lensing/cmblensing/des/selection/completeness_des.txt")
[PROFILES_TO_COMPARE]
plot_comparison = True
profiles = Battaglia16, Arnaud10
params = [(18.1, 0.154, -0.758, -0.3, 1.0, 4.35, 0.0393, 0.415, 0.497, -0.00865, 0.731),(14.347865720338445, 1.177, 0.3081, 1.051, 5.4905)]
profiles_name = Battaglia+16, Arnaud+10
method = stacked
eval_mass = [True, True]