[PRIORS]
\log_{10}{P_0} = free , flat_prior , 9 | 13
P_{M} = free , gaussian_prior_truncated, 0.66 | 0.5 | 0.1 | 3
P_{z} = free, gaussian_prior_truncated, 2.66 | 0.5 | 1 | 4
\log_{10}{\gamma_0} = free, gaussian_prior_truncated, -0.522 | 0.25 | -3 | 2
;, flat_prior , -1 | 1
gamma_M = free , t_student_prior_truncated, 1 | 0 | -7 | 7
gamma_z = free , t_student_prior_truncated, 1 | 0 | -7 | 7
beta = free, t_student_prior_truncated, 1 | 0 | 0 | 10
betaM = fixed, 0.0
betaz = fixed, 0.0
; t_student_prior_truncated, 1 | 0 | 0 | 6
alpha = free, gaussian_prior_truncated, 1.33 | 0.25 | 0 | 3.5
alphaM = fixed, 0.0
alphaz = fixed, 0.0
\log_{10}{c_{200,0}} = free, flat_prior, 0 | 1
c_{200,M} = free, t_student_prior_truncated, 1 | 0 | -4 | 4
;gaussian_prior_truncated, -0.50 | 0.2 | -2.5 | 2.5
c_{200,z} = free, t_student_prior_truncated, 1 | 0 | -4 | 4
;gaussian_prior_truncated, 0.12 | 0.61 | -2.5 | 2.5
;\log_{10}{r_s} = free , flat_prior , -0.2 | 0.4
[PRIORS_MIS_CENTERING]
f_{mis} = free, gaussian_prior_truncated , 0.26 | 0.05 | 0.0 | 0.6
; f_{M} = free, t_student_prior_truncated, 1 | 0 | -0.1 | 0.1
; f_{z} = free, t_student_prior_truncated, 1 | 0 | -0.1 | 0.1
sigma_{mis} = free, gaussian_prior_truncated , 0.35 | 0.05 | 0.1 | 1
[PRIORS_HALO_MODEL]
\log_{10}{A_{\lambda-M}} : free , gaussian_prior_truncated, 30 | 0.5 | 25 | 35
F_{\lambda} : free, gaussian_prior_truncated, 0.75 | 0.05 | 0.65 | 0.85
G_{z} : free, gaussian_prior_truncated, 0 | 0.01 | -1 | 1
[SIGMA_SYSTEMATIC]
sigma_{sys} = free, gaussian_prior_truncated, 0.0 | 0.1 | -1 | 1
[MODEL]
rbins = 35
zbins = 20
Mbins = 20
profile = ycompton_general3M200
richness_pivot = 32.68
redshift_pivot = 0.4737
mass_pivot = 14.35
two_halo_term = True
mis_centering = True
rebinning = True
use_sigma_sys = False
name = TSZ
y = $\langle_y \rangle$, 
x = R,arcmin
yscale = log
xscale = linear
ymin = 5e-8
ymax = 1e-4
title = ACT ycompton profile
model_name= GNFW
rotate_cov_matrix = False
use_filters = True
apply_filter_per_profile = False
filters = dict(apply_beam = dict(nr = 100))
off_diag = True
delta = 200
background = matter
eval_mass = True
legend_pos = center right
shrinkcage = False
alpha = 0.5
regularize = True
target_cond_number = 1000
numba = True
[EMCEE]
nwalkers = 50
nsteps = 20000
output_file = mcmc_samples_y_generalM200_final, h5
rewrite = True
delete = True
likelihood = gaussian
ncores = 39
store_two_halo_term = True
[BLOBS]
CHI2 = np.float64 , (1)
LN_PRIOR = np.float64 , (1)
LN_LIKELIHOOD = np.float64 , (1)
SIGNAL= np.float64 , (72)
ONE_HALO = np.float64, (72)
TWO_HALO = np.float64, (72)
[TWO_HALO_TERM]
R = 0.1, 30, 50, linear
M = 13, 16, 20, log
k = -15, 15, 50, log
background = matter
delta = 200
two_halo_power = False
two_halo_power_func = linear
eval_only_mass = False
eval_only_richness = False
eval_only_redshift = False
[PRIORS_TWO_HALO_POWER]
A_{2h} = free, flat_prior, 0 | 5
A_{z,2h} = free, t_student_prior_truncated, 1, 0, -2, 2
[MIS_CENTERING]
Roff = 0, 2, 10, linear
theta = 0, 6.28318, 10, linear
fixed = False
fmis = 0.246
params = 0.385
func = mis_centering_model
[REBINNING]
Nbins = 30
pixel_size = 0.5
method = spline
interpolation_kwargs = dict(k=1, s=0)
[COSMOLOGY]
Neff    = 3.044
Omega_b = 0.050
Omega_c = 0.253
h       = 0.679
n_s     = 0.960
sigma8  = 0.811
[COMPLETENESS]
use_redshift = True
eval_lambda_true = True
fixed_RM_relationship = True
load_from_file = False
func = 'P_lob_ltr'
rbins = 35
zbins = 25
Mbins = 25
max_lambda_true = 350
min_lambda_true = 10
Nlambda_obs = 30
Nlambda_true = 50
completeness_kwargs = dict(completenes_file = "/data2/cristobal/actpol/lensing/cmblensing/des/selection/completeness_des.txt")
[PROFILES_TO_COMPARE]
plot_comparison = False
profiles = Battaglia16, Arnaud10
params = [(8.403, 0.154, -0.758, -0.3, 1.0, 4.35, 0.0393, 0.415, 0.497, -0.00865, 0.731),(8.403, 1.177, 0.3081, 5.4905, 1.051)]
profiles_name = Battaglia+16, Arnaud+10
method = stacked
eval_mass = [True, True]